/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stlb10sheet;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amand
 */
public class stinfojfraame extends javax.swing.JFrame {

    /**
     * Creates new form stinfojfraame
     */
    public stinfojfraame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        indexnum = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        subject1 = new javax.swing.JLabel();
        subject2 = new javax.swing.JLabel();
        indexnumtf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        subject1tf = new javax.swing.JTextField();
        subject2tf = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        retrieve = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        retrievetext = new javax.swing.JTextArea();
        subject3 = new javax.swing.JLabel();
        gpa = new javax.swing.JLabel();
        subject3tf = new javax.swing.JTextField();
        gpatf = new javax.swing.JTextField();
        nextbut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-asif-methar-760645.jpg"))); // NOI18N
        jLabel2.setText("Index Number");
        jLabel2.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indexnum.setBackground(new java.awt.Color(255, 255, 255));
        indexnum.setForeground(new java.awt.Color(0, 0, 0));
        indexnum.setText("Index Number");
        jPanel1.add(indexnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 30));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, 30));

        subject1.setForeground(new java.awt.Color(0, 0, 0));
        subject1.setText("Subject 1");
        jPanel1.add(subject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, 30));

        subject2.setForeground(new java.awt.Color(0, 0, 0));
        subject2.setText("Subject 2");
        jPanel1.add(subject2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 100, 30));

        indexnumtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexnumtfActionPerformed(evt);
            }
        });
        jPanel1.add(indexnumtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 150, -1));

        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        jPanel1.add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, -1));

        subject1tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1tfActionPerformed(evt);
            }
        });
        jPanel1.add(subject1tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 150, -1));

        subject2tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject2tfActionPerformed(evt);
            }
        });
        jPanel1.add(subject2tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 150, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 120, 30));

        retrieve.setText("Retrieve");
        retrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveActionPerformed(evt);
            }
        });
        jPanel1.add(retrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 120, 30));

        retrievetext.setColumns(20);
        retrievetext.setRows(5);
        jScrollPane1.setViewportView(retrievetext);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 330, 360));

        subject3.setForeground(new java.awt.Color(0, 0, 0));
        subject3.setText("Subject 3");
        jPanel1.add(subject3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 110, 20));

        gpa.setForeground(new java.awt.Color(0, 0, 0));
        gpa.setText("GPA");
        jPanel1.add(gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 110, 30));

        subject3tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject3tfActionPerformed(evt);
            }
        });
        jPanel1.add(subject3tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 150, -1));

        gpatf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpatfActionPerformed(evt);
            }
        });
        jPanel1.add(gpatf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 150, -1));

        nextbut.setText("Next");
        nextbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbutActionPerformed(evt);
            }
        });
        jPanel1.add(nextbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 140, 30));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Student Detail Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indexnumtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexnumtfActionPerformed
        
    }//GEN-LAST:event_indexnumtfActionPerformed

    private void subject2tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject2tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject2tfActionPerformed

    private void subject3tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject3tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject3tfActionPerformed

    private void gpatfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpatfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpatfActionPerformed

    private void retrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveActionPerformed
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/STinfo", "root", "Amie233#")) {
        String sql = "SELECT student_name FROM StudentData"; // Retrieve all names
        var stmt = conn.prepareStatement(sql);
        var rs = stmt.executeQuery();

        StringBuilder namesList = new StringBuilder();
        while (rs.next()) {
            String name = rs.getString("student_name");
            namesList.append(name).append("\n"); // Append each name to a list
        }

        if (namesList.length() > 0) {
            retrievetext.setText("All Student Names:\n" + namesList.toString()); // Display the list of names
        } else {
            JOptionPane.showMessageDialog(this, "No students found in the database.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error connecting to the database: " + e.getMessage());
        e.printStackTrace(); // Consider logging or handling the exception explicitly
    }
    }//GEN-LAST:event_retrieveActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String indexNumber = indexnumtf.getText();
        String name = nametf.getText();
        String subject1 = subject1tf.getText();
        String subject2 = subject2tf.getText();
        String subject3 = subject3tf.getText();
        String gpa = gpatf.getText();

        indexnumtf.setText("");
        nametf.setText("");
        subject1tf.setText("");
        subject2tf.setText("");
        subject3tf.setText("");
        gpatf.setText("");

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/STinfo", "root", "Amie233#")) {
            // Create a PreparedStatement to insert the data into the database
            String sql = "INSERT INTO StudentData VALUES(?, ?, ?, ?, ?, ?)";
            var stmt = conn.prepareStatement(sql);
            stmt.setString(1, indexNumber);
            stmt.setString(2, name);
            stmt.setString(3, subject1);
            stmt.setString(4, subject2);
            stmt.setString(5, subject3);
            stmt.setString(6, gpa);

            // Execute the PreparedStatement to insert the data into the database
            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Student added to the database Successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Error adding student to the database.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error connecting to the database: " + e.getMessage());
        }

    }//GEN-LAST:event_saveActionPerformed

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    private void subject1tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject1tfActionPerformed

    private void nextbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbutActionPerformed
        Searchjf js = new Searchjf();
        js.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nextbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String url = "stdetails://localhost:3306/STinfo";
        String user = "root";
        String password = "Amie233#";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            DriverManager.getConnection(url, user, password);
        } catch(Exception e){
            System.out.println(e);
        }
        
//        createNewTable();
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stinfojfraame().setVisible(true);
            }
        });
    }
    
    
//    public static void createNewTable() {
//        
//        String dropsql = "DROP TABLE IF EXISTS employees";
//            try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/STinfo","root", "Amie233#");
//                 Statement statement = connection.createStatement()) {
//                statement.execute(dropsql);
//            } catch (SQLException e) {
//                System.out.println(e.getMessage());
//            }
//
//        // SQL statement for creating a new table
//        String sql = "CREATE TABLE IF NOT EXISTS employees (" +
//                "id INT PRIMARY KEY AUTO_INCREMENT," +
//                "index_number INT(20) NOT NULL, " +
//                "name VARCHAR(255) NOT NULL," +
//                "gpa DECIMAL(3,2)," +
//                "Subject1 VARCHAR(255)," +
//                "Subject2 VARCHAR(255)," +
//                "Subject3 VARCHAR(255)" +
//                ")";
//        
//        try {
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stdetails", "root", "Amie233#");
//            Statement stmt = conn.createStatement();
//            stmt.execute(sql);
//            System.out.println("Table 'employees' created successfully.");
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gpa;
    private javax.swing.JTextField gpatf;
    private javax.swing.JLabel indexnum;
    private javax.swing.JTextField indexnumtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametf;
    private javax.swing.JButton nextbut;
    private javax.swing.JButton retrieve;
    private javax.swing.JTextArea retrievetext;
    private javax.swing.JButton save;
    private javax.swing.JLabel subject1;
    private javax.swing.JTextField subject1tf;
    private javax.swing.JLabel subject2;
    private javax.swing.JTextField subject2tf;
    private javax.swing.JLabel subject3;
    private javax.swing.JTextField subject3tf;
    // End of variables declaration//GEN-END:variables
}
